Repository devXprite/gitglance, pull requests merged in 2024-05, with the labels that each got.

#20 docs: Update Readme
  README.md
Labels: documentation, GGSoC'24, level-1

#25 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, GGSoC'24, level1

#34 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, GGSoC'24

#43 fixed changes in the contributors as said
  app/(home)/contributors.js
  app/(home)/page.js
  next.config.mjs
Labels: GGSoC, level1
